config/routes.rb
Rails.application.routes.draw do
  resources :routers
  namespace :admin, path: 'admin' do
    resources :devtypes
    resources :device_types
    resources :mappings
    resources :devices do 
      resources :backups do
        resources :configs
      end
    end
  end
  namespace :api, :defaults => {:format => :xml} do
    namespace :v1 do
      match 'text_test' => 'twilio#text_engine', via: [:post]
      # match 'received_fax' => 'director#received_fax', via: [:post]
      # match 'incoming_fax' => 'director#received_fax', via: [:post]
      # match 'add_clip' => 'director#add_clip', via: [:post]
      # match 'query_hold_music_exists' => 'director#query_hold_music_exists', via: [:post]
      # match 'query_sound_clip_exists' => 'director#query_sound_clip_exists', via: [:post]
      # match 'query_fax_exists' => 'director#query_fax_exists', via: [:post]
      # match 'sync_streams' => 'director#sync_streams', via: [:post]
      # match 'update_stream' => 'director#update_stream', via: [:post]
      # match 'create_stream' => 'director#create_stream', via: [:post]
      # match 'remove_stream' => 'director#remove_stream', via: [:post]
      # match 'add_sound_clip' => 'director#add_sound_clip', via: [:post]
      # match 'remove_sound_clip' => 'director#remove_sound_clip', via: [:post]
      # match 'add_hold_music' => 'director#add_hold_music', via: [:post]
      # match 'remove_hold_music' => 'director#remove_hold_music', via: [:post]
      # match 'add_fax' => 'director#add_fax', via: [:post]
      # match 'remove_fax' => 'director#remove_fax', via: [:post]
      # match 'retry_fax' => 'director#retry_fax', via: [:post]
      # match 'update_fax' => 'director#update_fax', via: [:post]
      # match 'pull_config' => 'director#pull_config', via: [:post]
      # match 'fax_success' => 'director#fax_success', via: [:post]
      # match 'fax_failed' => 'director#fax_failed', via: [:post]
      # match 'sync_queue' => 'director#sync_queue', via: [:post]
      # match 'remove_queue' => 'director#remove_queue', via: [:post]
      # match '/*desired_action' => 'director#director', via: [:get, :post, :put]
      # # resources :director
      # root :to => 'director#index'
    end
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @testing = { testing1: "one", testing2: "two", testing3: "three" }
  end
end

app/views/visitors/_sidebar.html.haml
%li.disabled
  = link_to root_path, title: "current_customer.to_s" do
    = fa_icon "male"
    %span.hidden-xs.hidden-sm= "current_customer.full_name"

%li{class: (active_tab == 'general') ? 'active' : nil}
  = link_to root_path(anchor: 'general'), title: 'Dashboard', data: {toggle: 'tab'} do
    = fa_icon "tachometer"
    %span.hidden-xs.hidden-sm Dashboard

- if true #can?(:index, Subscription)
  %li{class: (active_tab == 'subscriptions') ? 'active' : nil}
    = link_to root_path, title: 'Subscriptions' do
      = fa_icon 'repeat'
      %span.hidden-xs.hidden-sm Subscriptions

- if true #can?(:index, Contract)
  %li{class: (active_tab == 'contracts') ? 'active' : nil}
    = link_to root_path, title: 'My Agreement' do
      = fa_icon 'gavel'
      %span.hidden-xs.hidden-sm My Agreement

- if true #can?(:index, CreditCard)
  %li{class: (active_tab == 'credit_cards') ? 'active' : nil}
    = link_to root_path, title: 'Credit Cards' do
      = fa_icon 'credit-card'
      %span.hidden-xs.hidden-sm Credit Cards

- if true #can?(:index, Document)
  %li{class: (active_tab == 'documents') ? 'active' : nil}
    = link_to root_path, title: 'Documents' do
      = fa_icon "folder-o"
      %span.hidden-xs.hidden-sm Documents

%li{class: (active_tab == 'tickets') ? 'active' : nil}
  = link_to root_path, title: 'Tickets' do
    = fa_icon "fire-extinguisher"
    %span.hidden-xs.hidden-sm Support

app/views/visitors/_toolbar.html.haml
I am the toolbar

app/views/visitors/index.html.haml
/ / - title "Active Customers", true, {fa_icon: 'male'}
- content_for(:sidebar) do
  = render 'sidebar', active_tab: 'general'
- content_for(:toolbar) do 
  = render 'toolbar'
- content_for(:subtitle) do
  "I am the subtitle"
- if current_user.admin?
  .tab-content
    .tab-pane.active#general
      .panel.panel-default
        .panel-heading
          %h4 Configuration Backups
        .panel-body
          = link_to "Manage Configuration Backups", admin_device_backups_path(1)
  .tab-content
    .tab-pane.active#general
      .panel.panel-default
        .panel-heading
          %h4 Device Management
        .panel-body
  .tab-content
    .tab-pane.active#general
      .panel.panel-default
        .panel-heading
          %h4 Log Lookup
        .panel-body
  .tab-content
    .tab-pane.active#general
      .panel.panel-default
        .panel-heading
          %h4 Manage Text Responders
        .panel-body
- else
  .tab-content
    .tab-pane.active#general
      .panel.panel-default
        .panel-heading
          %h4 Nothing to see here 
        .panel-body