config/routes.rb
Rails.application.routes.draw do
  resources :routers
  namespace :admin, path: 'admin' do
    resources :devtypes
    resources :device_types
    resources :mappings
    resources :devices do 
      resources :backups do
        resources :configs
      end
    end
  end
  namespace :api, :defaults => {:format => :xml} do
    namespace :v1 do
      match 'text_test' => 'twilio#text_engine', via: [:post]
      # match 'received_fax' => 'director#received_fax', via: [:post]
      # match 'incoming_fax' => 'director#received_fax', via: [:post]
      # match 'add_clip' => 'director#add_clip', via: [:post]
      # match 'query_hold_music_exists' => 'director#query_hold_music_exists', via: [:post]
      # match 'query_sound_clip_exists' => 'director#query_sound_clip_exists', via: [:post]
      # match 'query_fax_exists' => 'director#query_fax_exists', via: [:post]
      # match 'sync_streams' => 'director#sync_streams', via: [:post]
      # match 'update_stream' => 'director#update_stream', via: [:post]
      # match 'create_stream' => 'director#create_stream', via: [:post]
      # match 'remove_stream' => 'director#remove_stream', via: [:post]
      # match 'add_sound_clip' => 'director#add_sound_clip', via: [:post]
      # match 'remove_sound_clip' => 'director#remove_sound_clip', via: [:post]
      # match 'add_hold_music' => 'director#add_hold_music', via: [:post]
      # match 'remove_hold_music' => 'director#remove_hold_music', via: [:post]
      # match 'add_fax' => 'director#add_fax', via: [:post]
      # match 'remove_fax' => 'director#remove_fax', via: [:post]
      # match 'retry_fax' => 'director#retry_fax', via: [:post]
      # match 'update_fax' => 'director#update_fax', via: [:post]
      # match 'pull_config' => 'director#pull_config', via: [:post]
      # match 'fax_success' => 'director#fax_success', via: [:post]
      # match 'fax_failed' => 'director#fax_failed', via: [:post]
      # match 'sync_queue' => 'director#sync_queue', via: [:post]
      # match 'remove_queue' => 'director#remove_queue', via: [:post]
      # match '/*desired_action' => 'director#director', via: [:get, :post, :put]
      # # resources :director
      # root :to => 'director#index'
    end
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/controllers/device_types_controller.rb
class DeviceTypesController < ApplicationController
  before_action :set_device_type, only: [:show, :edit, :update, :destroy]

  # GET /device_types
  # GET /device_types.json
  def index
    @device_types = DeviceType.all
  end

  # GET /device_types/1
  # GET /device_types/1.json
  def show
  end

  # GET /device_types/new
  def new
    @device_type = DeviceType.new
  end

  # GET /device_types/1/edit
  def edit
  end

  # POST /device_types
  # POST /device_types.json
  def create
    @device_type = DeviceType.new(device_type_params)

    respond_to do |format|
      if @device_type.save
        format.html { redirect_to @device_type, notice: 'Device type was successfully created.' }
        format.json { render :show, status: :created, location: @device_type }
      else
        format.html { render :new }
        format.json { render json: @device_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device_types/1
  # PATCH/PUT /device_types/1.json
  def update
    respond_to do |format|
      if @device_type.update(device_type_params)
        format.html { redirect_to @device_type, notice: 'Device type was successfully updated.' }
        format.json { render :show, status: :ok, location: @device_type }
      else
        format.html { render :edit }
        format.json { render json: @device_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device_types/1
  # DELETE /device_types/1.json
  def destroy
    @device_type.destroy
    respond_to do |format|
      format.html { redirect_to device_types_url, notice: 'Device type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device_type
      @device_type = DeviceType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_type_params
      params.require(:device_type).permit(:name, :model, :manufacturer)
    end
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
end

app/views/device_types/_form.html.haml
= simple_form_for(@device_type) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :model
    = f.input :manufacturer

  .form-actions
    = f.button :submit

app/views/device_types/edit.html.haml
%h1 Editing device_type

= render 'form'

= link_to 'Show', @device_type
\|
= link_to 'Back', device_types_path

app/views/device_types/index.html.haml
%h1 Listing device_types

%table
  %thead
    %tr
      %th Name
      %th Model
      %th Manufacturer
      %th
      %th
      %th

  %tbody
    - @device_types.each do |device_type|
      %tr
        %td= device_type.name
        %td= device_type.model
        %td= device_type.manufacturer
        %td= link_to 'Show', device_type
        %td= link_to 'Edit', edit_device_type_path(device_type)
        %td= link_to 'Destroy', device_type, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Device type', new_device_type_path

app/views/device_types/new.html.haml
%h1 New device_type

= render 'form'

= link_to 'Back', device_types_path

app/views/device_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @device_type.name
%p
  %b Model:
  = @device_type.model
%p
  %b Manufacturer:
  = @device_type.manufacturer

= link_to 'Edit', edit_device_type_path(@device_type)
\|
= link_to 'Back', device_types_path