releases/20150428000540/config/routes.rb
Rails.application.routes.draw do
  resources :devices
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

releases/20150428000540/app/models/device.rb
class Device < ActiveRecord::Base
end

releases/20150428000540/app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

releases/20150428000540/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

releases/20150428000540/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :description, :ip_address, :device_status, :ipv6, :snmp_template)
    end
end

releases/20150428000540/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

releases/20150428000540/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

releases/20150428000540/app/helpers/application_helper.rb
module ApplicationHelper
end

releases/20150428000540/app/helpers/devices_helper.rb
module DevicesHelper
end

releases/20150428000540/app/views/devices/_form.html.haml
= simple_form_for(@device) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :ip_address
    = f.input :device_status
    = f.input :ipv6
    = f.input :snmp_template

  .form-actions
    = f.button :submit

releases/20150428000540/app/views/devices/edit.html.haml
%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

releases/20150428000540/app/views/devices/index.html.haml
%h1 Listing devices

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Ip address
      %th Device status
      %th Ipv6
      %th Snmp template
      %th
      %th
      %th

  %tbody
    - @devices.each do |device|
      %tr
        %td= link_to device.name, device_path(device)
        %td= link_to device.description, device_path(device)
        %td= link_to device.ip_address, device_path(device)
        %td= link_to device.device_status, device_path(device)
        - if device.ipv6? 
          %td= link_to "True", device_path(device)
        - else 
          %td= ""
        - if device.snmp_template.blank? 
          %td= link_to "None", device_path(device)
        - else 
          %td= ""
        %td= link_to 'Show', device
        %td= link_to 'Edit', edit_device_path(device)
        %td= link_to 'Destroy', device, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Device', new_device_path

releases/20150428000540/app/views/devices/new.html.haml
%h1 New device

= render 'form'

= link_to 'Back', devices_path

releases/20150428000540/app/views/devices/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @device.name
%p
  %b Description:
  = @device.description
%p
  %b Ip address:
  = @device.ip_address
%p
  %b Device status:
  = @device.device_status
%p
  %b Ipv6:
  = @device.ipv6
%p
  %b Snmp template:
  = @device.snmp_template

= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path

releases/20150428000540/app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

releases/20150428000540/app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

releases/20150428000540/app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>